spring:
  application:
    name: eureka-client
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/,http://localhost:8763/eureka/ # 服务注册地址
      # 开启健康检查（依赖spring-boot-starter-actuator）
    healthcheck:
      enabled: true
  instance:
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 15
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5

